### ISSUE TITLE
hdurl=""への対応

### ISSUE THREAD

**Issue by stshf** [Recursion-teamdev-go-lang-teamc/space-app#31]
## 📋 説明

youtubeのリンクが返ってくるケース
youtubeのサムネイルを表示し、クリックするとyoutubeに飛ぶようにするなど、対応を検討し、実装する
![image](https://github.com/user-attachments/assets/aaade916-52bf-4ca6-af47-f8f60ba60db2)

その他のURLが返ってくるケース
- e.g) https://www.meteorshowers.org/view/iau-7

**Comment by mumiso710** [comment]
https://developer.mozilla.org/ja/docs/Web/HTML/Element/iframe

これ使ったら埋め込み自体はできます

**Comment by stshf** [comment]
方針
- [ ] `hdurl==""`の場合が、responseに画像が入っていないケース。この場合は、htmlの<iframe>を使用
- [ ] 画面に応じて、埋め込みの制御をする
  - [ ] 一覧画面では、pointer-event: noneの設定にして、埋め込みが操作できないようにする
  - [ ] 詳細画面では、埋め込みが操作できるようにする（動画再生、サイト閲覧など）
